checkmeinsu/checkmeinsu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^superuser/', include('superuser.urls', namespace ='superuser')),
    url(r'^patients/', include('patients.urls', namespace ='patients')),
]

checkmeinsu/patients/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views


urlpatterns = [
    url(r'^$', views.patientview, name='patient'),
    url(r'^create/$', views.create_patient, name='create_patient'),
    url(r'^(?P<patient_id>\d+)/$', views.patient_detail, name='patient_detail'),
    url(r'^(?P<patient_id>\d+)/edit/$', views.edit_patient, name='edit_patient'),
    url(r'^(?P<patient_id>\d+)/delete/$', views.delete_patient, name='delete_patient'),
]

checkmeinsu/superuser/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.superuser, name='superuser'),
    url(r'^userpage/$', views.userpage, name='userpage'),
    url(r'^configuration/$', views.configuration, name='configuration'),
    url(r'^userform/$', views.userform, name='userform'),
]

checkmeinsu/patients/models.py
from django.db import models


class Patient (models.Model):
    #required
    last_name=models.CharField(max_length=50)
    first_name=models.CharField(max_length=50)
    phone_number=models.CharField(max_length=50)
    phone_type=models.CharField(max_length=50)

    #optional
    street1=models.CharField(max_length=150, blank=True)
    street2=models.CharField(max_length=150, blank=True)
    city=models.CharField(max_length=50, blank=True)
    state=models.CharField(max_length=2, blank=True)
    zip_zip=models.CharField(max_length=5, blank=True)
    second_number=models.CharField(max_length=50, blank=True)
    second_type=models.CharField(max_length=50, blank=True)
    email=models.EmailField(blank = True)
    insurance=models.CharField(max_length=50, blank=True)


# Create your models here.

checkmeinsu/superuser/models.py
from django.db import models

# Create your models here.

checkmeinsu/patients/forms.py
from django import forms

from .models import Patient


class PatientForm(forms.ModelForm):
    class Meta:
        model=Patient
        fields=("last_name","first_name","phone_number","phone_type","street1",
        "street2","city","state","zip_zip","second_number","second_type","email",
        "insurance"
        )


class DeleteNewForm(forms.ModelForm):
    class Meta:
        model=Patient
        fields=()

checkmeinsu/patients/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect

from .forms import PatientForm, DeleteNewForm
from .models import Patient


def patientview(request):
    patients=Patient.objects.all()
    return render(request, "patient.html", {'patients':patients})


def create_patient(request):
    if request.method=="GET":
        form=PatientForm()
        return render(request, "create_patient.html", {'form': form})

    elif request.method =="POST":
        form=PatientForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("patients:patient")

        else:
            return render(request, "create_patient.html", {'form': form})


def patient_detail(request, patient_id):
    patient=get_object_or_404(Patient, id=patient_id)
    return render(request, "patient_detail.html", {'patient':patient})


def edit_patient(request, patient_id):
    if request.method=='GET':
        patient=get_object_or_404(Patient, id=patient_id)
        form=PatientForm(instance=patient)
        return render(request, "edit_patient.html", {'form': form, 'patient':patient})

    elif request.method=='POST':
        patient=get_object_or_404(Patient, id=patient_id)
        form=PatientForm(request.POST, instance=patient)

        if form.is_valid():
            form.save()
            return redirect("patients:patient_detail", patient.id)

        else:
            return render(request, "edit_patient.html", {'form': form})


def delete_patient(request, patient_id):
    patient=get_object_or_404(Patient, id=patient_id)

    if request.method=='POST':
        form=DeleteNewForm(request.POST, instance=patient)

        if form.is_valid():
            patient.delete()
            return HttpResponseRedirect("/")

    else:
        form = DeleteNewForm(instance=patient)
        return HttpResponseRedirect("/patients/")
        #return render({'patients': patient})

# Create your views here.

checkmeinsu/superuser/views.py
from django.shortcuts import render


def superuser(request):
    return render(request, 'superuser.html')

def userpage(request):
    return render(request, 'userpage.html')

def configuration(request):
    return render(request, 'configurationpage.html')

def userform(request):
    return render(request, 'userform.html')

# Create your views here.

checkmeinsu/patients/templates/create_patient.html
<html>
  <head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  </head>
    <body>
      <h1>Create New Patient </h1>
        <form action="" method ="POST">
          {% csrf_token %}
          <div class = "input-group">
            <label>{{ form.last_name.label}}</label>
            {{patient.last_name|capfirst }}
          </div>
          <div class = "input-group">
            <label>{{ form.first_name.label}}</label>
            {{ patient.first_name |capfirst }}
          </div>
          <div class = "input-group">
            <label>{{ form.phone_number.label}}</label>
            {{ form.phone_number}}
            {% if patient.phone_number < 9 %}
              Please put in full phone number
            {% endif %}
          </div>
          <div class = "input-group">
            <label>{{ form.phone_type.label}}</label>
            {{ form.phone_type}}

          </div>
          <div class = "input-group">
            <label>{{ form.street1.label}}</label>
            {{ form.street1}}
          </div>
          <div class = "input-group">
            <label>{{ form.street2.label}}</label>
            {{ form.street2}}
          </div>
          <div class = "input-group">
            <label>{{ form.city.label}}</label>
            {{ form.city}}
          </div>
          <div class = "input-group">
            <label>{{ form.state.label}}</label>
            {{ form.state}}
          </div>
          <div class = "input-group">
            <label>{{ form.zip_zip.label}}</label>
            {{ form.zip_zip}}
          </div>
          <div class = "input-group">
            <label>{{ form.second_number.label}}</label>
            {{ form.second_number}}
          </div>
          <div class = "input-group">
            <label>{{ form.second_type.label}}</label>
            {{ form.second_type}}
          </div>
          <div class = "input-group">
            <label>{{ form.email.label}}</label>
            {{ form.email}}
          </div>
          <div class = "input-group">
            <label>{{ form.insurance.label}}</label>
            {{ form.insurance}}
          </div>
          <button type ="submit">Submit</button>
        </form>
    </body>
</html>

checkmeinsu/patients/templates/edit_patient.html
<html>
  <head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  </head>
    <body>
      <h1>{{ patient.first_name }} {{ patient.last_name }} </h1>
        <form action="" method ="POST">
          {% csrf_token %}
          <div class = "input-group">
            <label>{{ form.last_name.label }}</label>
            {{ form.last_name }}
          </div>
          <div class = "input-group">
            <label>{{ form.first_name.label}}</label>
            {{ form.first_name }}
          </div>
          <div class = "input-group">
            <label>{{ form.phone_number.label }}</label>
            {{ form.phone_number }}
          </div>
          <div class = "input-group">
            <label>{{ form.phone_type.label }}</label>
            {{ form.phone_type }}
          </div>
          <div class = "input-group">
            <label>{{ form.street1.label }}</label>
            {{ form.street1 }}
          </div>
          <div class = "input-group">
            <label>{{ form.street2.label }}</label>
            {{ form.street2 }}
          </div>
          <div class = "input-group">
            <label>{{ form.city.label }}</label>
            {{ form.city }}
          </div>
          <div class = "input-group">
            <label>{{ form.state.label }}</label>
            {{ form.state }}
          </div>
          <div class = "input-group">
            <label>{{ form.zip_zip.label }}</label>
            {{ form.zip_zip }}
          </div>
          <div class = "input-group">
            <label>{{ form.second_number.label }}</label>
            {{ form.second_number }}
          </div>
          <div class = "input-group">
            <label>{{ form.second_type.label }}</label>
            {{ form.second_type }}
          </div>
          <div class = "input-group">
            <label>{{ form.email.label }}</label>
            {{ form.email }}
          </div>
          <div class = "input-group">
            <label>{{ form.insurance.label }}</label>
            {{ form.insurance }}
          </div>
          <button type ="submit">Submit</button>
        </form>
    </body>
</html>

checkmeinsu/patients/templates/patient.html
<html>
  <h1>Patient Models View</h1>
    <body>
        {% for patient in patients %}
          <ul>
              <li><a href="{% url 'patients:patient_detail' patient.id %}">
                {{ patient.last_name|capfirst }}</a></li>
              <li>{{ patient.first_name|capfirst }}</li>
              <li>{{ patient.phone_number }}</li>
              <li>{{ patient.phone_type }}</li>
              <li>{{ patient.street1 }}</li>
              <li>{{ patient.street2 }}</li>
              <li>{{ patient.city }}</li>
              <li>{{ patient.state }}</li>
              <li>{{ patient.zip_zip }}</li>
              <li>{{ patient.second_number }}</li>
              <li>{{ patient.second_type }}</li>
              <li>{{ patient.email }}</li>
              <li>{{ patient.insurance }}</li>
          </ul>
        {% endfor %}
      </body>
</html>

checkmeinsu/patients/templates/patient_detail.html
<html>
  <body>
    <h1>{{ patient.first_name|capfirst }} {{ patient.last_name|capfirst }}</h1>
    <p>Email: {{ patient.email }}</p>
    <p>Phone Number: {{ patient.phone_number }}</p>
    <p><a href = "{% url 'patients:edit_patient' patient.id %}">Edit This Record</a></p>
    <p><a href = "{% url 'patients:delete_patient' patient.id %}">Delete This Record</a></p>
  </body>
</html>

checkmeinsu/superuser/templates/configurationpage.html
{% load staticfiles %}
<html>
<head>
<center><title> Check Me IN: Medical Check In Software</title>
<h1>Check Me IN: Medical Check In Software</h1>

<h2>Configuration</h2></center>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href= {% static 'css/superusercss.css' %}>
</head>
<br></br>
<body class="body">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				Site Title<input name="sitetitle" class="form-control" type="text" maxlength="55" size="35">
				Set Admin Email<input name="email" class="form-control" type="text" maxlength="75" size="35">
				TimeZone: <select name="timezone" class="form-control" >
					<option value="3600" selected="">Eastern</option>
					<option value="">Central</option>
					<option value="-3600">Mountain</option>
					<option value="-7200">Pacific</option>
					</select>
		</div>
	</div>
<br></br>
		<div class="row">
			<div class="col-md-2">
				<h5><b>Apt Time</b></h5>
					<input type="text" class="form-control" name="c1r1" placeholder="" value="9:30 AM">
					<input type="text" class="form-control" name="c1r2" placeholder=""value="10:00AM">
					<input type="text" class="form-control" name="c1r3" placeholder="Time 3" value="">
					<input type="text" class="form-control"name="c1r4"  placeholder="Time 4" value="">
					<input type="text" class="form-control"name="c1r5"  placeholder="" value="">
					<input type="text" class="form-control"name="c1r6"  placeholder="" value="">
					<input type="text" class="form-control"name="c1r7"  placeholder="" value="">
			</div>
			<div class="col-md-2">
				<h5><b>Providers</b></h5>
					<input type="text" class="form-control" name="c2r1" placeholder=""  value="Dr. Eric Cartman">
					<input type="text" class="form-control" name="c2r2" placeholder=""  value="Dr. Stephen King ">
					<input type="text" class="form-control" name="c2r3" placeholder=""  value="Dr. Ripley">
					<input type="text" class="form-control" name="c2r4" placeholder="Provider 4"  value="">
					<input type="text" class="form-control" name="c2r5" placeholder="Provider 5"  value="">
					<input type="text" class="form-control" name="c2r6" placeholder=""  value="">
			</div>
			<div class="col-md-2">
				<h5><b>Facility</b></h5>
					<input type="text" class="form-control" name="c3r1" placeholder="" value=" Dental">
					<input type="text" class="form-control" name="c3r2" placeholder="" value="Behavioral Healh ">
					<input type="text" class="form-control" name="c3r3" placeholder="" value="Medical">
					<input type="text" class="form-control" name="c3r4" placeholder="Facility 4"value="">
			</div>
		</div>
<br></br>
		<div class="row">
			<div class="col-sm-2">
				<div class="checkbox">
					<b>Check to Make Mandatory</b><br></br>
						<input type="checkbox"> Name</input><br></br>
						<input type="checkbox"> DOB</input><br></br>
						<input type="checkbox"> Address</input><br></br>
						<input type="checkbox">Phone Number</input><br></br>
						<input type="checkbox"> Email</input><br></br>
						<input type="checkbox"> Appointment Time</input><br></br>
						<input type="checkbox"> Provider</input><br></br>
						<input type="checkbox"> Facility</input><br></br>

				</div>
			</div>
		</div>
	</div>
</body>
</html>

checkmeinsu/superuser/templates/superuser.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<center><title> Check Me IN: Medical Check In Software</title>
<h1>Check Me IN: Medical Check In Software</h1>

<h2>Superuser</h2></center>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href= {% static 'css/superusercss.css' %}>
</head>
<body class="body">
<br>
<br>
	<center>
		<div class="container">
			<div class="row spacing"><a class="button1" href= {% url 'superuser:userpage' %}><button class="button1 button">Users</button></a></div>
			<div class="row spacing"><a class="button1" href= {% url 'superuser:configuration' %}><button class="button1 button">Configuration</button></a></div>
			<div class="row spacing"><button class="button1 button">Reports</button></div>
		</div>

	</center>
</body>
</html>

checkmeinsu/superuser/templates/userform.html
{% load staticfiles %}
<html>
<head>
<center><title> Check Me IN: Medical Check In Software</title>
<h1>Check Me IN: Medical Check In Software</h1>

<h2>Users</h2></center>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href= {% static 'css/superusercss.css' %}>
</head>
<br></br>
<body class="body">
	<center>
		<form class="form-inline">
			<div class="form-group">
				<label class="sr-only" for="exampleInputUser Name">User Name</label>
					<input type="User Name" class="form-control" id="exampleInputUser Name" placeholder="User Name">
			</div>
			<div class="form-group">
				<label class="sr-only" for="exampleInputPassword3">Password</label>
					<input type="password" class="form-control" id="exampleInputPassword3" placeholder="Password">
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox"> Make Admin
				</label>
			</div>

		</form>
		<a class="button1" href="userpage.html"><button class="button1 button">Add/Edit User</button></a>
	</center>
</body>
</html>

checkmeinsu/superuser/templates/userpage.html
{% load staticfiles %}
<html>

<head>
<center><title> Check Me IN: Medical Check In Software</title>
<h1>Check Me IN: Medical Check In Software</h1>

<h2>Users</h2></center>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href= {% static 'css/superusercss.css' %}>
</head><br></br>
<body class="body">
	<center>
		<table class="table table-bordered table1">
			<tbody>
				<tr>
					<th>User Name</th>
					<th>Admin</th></div>
					<th>Edit</th></div>
					<th>Delete</th></div>
				</tr>
				<tr>
					<td>kboyle</td>
					<td>Yes</td>
					<td><a class="button1" href= {% url 'superuser:userform' %}><button class="button1 button">Edit</button></a></td>
					<td><button class="button1 button">Delete</button></td>
				</tr>
				<tr>
					<td>mboston</th>
					<td>No</th>
					<td><a class="button1" href= {% url 'superuser:userform' %}><button class="button1 button">Edit</button></a></td>
					<td><button class="button1 button">Delete</button></td>
				</tr>
				<tr>
					<td colspan="4">  <center>
						<a href="link">Add New User</a></center>
					</td>
				<tr>
			</tbody>
		</table>
	</center>
</body>
</html>